using HRMS.Application.DTOs;
using HRMS.Domain.Entities;
using HRMS.Domain.Interfaces;

namespace HRMS.Application.Services;

public class SalaryAdjustmentService
{
    private readonly ISalaryAdjustmentRepository _adjustmentRepository;
    private readonly IEmployeeRepository _employeeRepository;

    public SalaryAdjustmentService(
        ISalaryAdjustmentRepository adjustmentRepository,
        IEmployeeRepository employeeRepository)
    {
        _adjustmentRepository = adjustmentRepository;
        _employeeRepository = employeeRepository;
    }

    public async Task<SalaryAdjustmentDto?> GetByIdAsync(Guid id)
    {
        var entity = await _adjustmentRepository.GetByIdAsync(id);
        return entity == null ? null : MapToDto(entity);
    }

    public async Task<IEnumerable<SalaryAdjustmentDto>> GetByMonthAsync(string yearMonth)
    {
        var entities = await _adjustmentRepository.GetByMonthAsync(yearMonth);
        return entities.Select(MapToDto);
    }

    public async Task<IEnumerable<SalaryAdjustmentDto>> GetByEmployeeAndMonthAsync(Guid employeeId, string yearMonth)
    {
        var entities = await _adjustmentRepository.GetByEmployeeAndMonthAsync(employeeId, yearMonth);
        return entities.Select(MapToDto);
    }

    public async Task<SalaryAdjustmentDto> CreateAsync(CreateSalaryAdjustmentDto dto)
    {
        var employee = await _employeeRepository.GetByIdAsync(dto.EmployeeId)
            ?? throw new InvalidOperationException("员工不存在");

        var entity = new SalaryAdjustment
        {
            EmployeeId = dto.EmployeeId,
            YearMonth = dto.YearMonth.Trim(),
            AdjustmentType = dto.AdjustmentType.Trim(),
            Amount = dto.Amount,
            SourceType = dto.SourceType,
            SourceId = dto.SourceId,
            IsAutoGenerated = dto.IsAutoGenerated,
            Remark = dto.Remark,
            CreatedBy = dto.CreatedBy
        };

        var created = await _adjustmentRepository.CreateAsync(entity);
        created.Employee = employee;
        return MapToDto(created);
    }

    public async Task<SalaryAdjustmentDto?> UpdateAsync(UpdateSalaryAdjustmentDto dto)
    {
        var entity = await _adjustmentRepository.GetByIdAsync(dto.Id);
        if (entity == null)
        {
            return null;
        }

        var employee = await _employeeRepository.GetByIdAsync(dto.EmployeeId)
            ?? throw new InvalidOperationException("员工不存在");

        entity.EmployeeId = dto.EmployeeId;
        entity.YearMonth = dto.YearMonth.Trim();
        entity.AdjustmentType = dto.AdjustmentType.Trim();
        entity.Amount = dto.Amount;
        entity.SourceType = dto.SourceType;
        entity.SourceId = dto.SourceId;
        entity.IsAutoGenerated = dto.IsAutoGenerated;
        entity.Remark = dto.Remark;
        entity.UpdatedBy = dto.UpdatedBy;

        await _adjustmentRepository.UpdateAsync(entity);
        entity.Employee = employee;
        return MapToDto(entity);
    }

    private static SalaryAdjustmentDto MapToDto(SalaryAdjustment entity)
    {
        return new SalaryAdjustmentDto
        {
            Id = entity.Id,
            EmployeeId = entity.EmployeeId,
            EmployeeNo = entity.Employee?.EmployeeNo ?? string.Empty,
            EmployeeName = entity.Employee?.Name ?? string.Empty,
            YearMonth = entity.YearMonth,
            AdjustmentType = entity.AdjustmentType,
            Amount = entity.Amount,
            SourceType = entity.SourceType,
            SourceId = entity.SourceId,
            IsAutoGenerated = entity.IsAutoGenerated,
            Remark = entity.Remark,
            CreatedBy = entity.CreatedBy,
            CreatedAt = entity.CreatedAt,
            UpdatedBy = entity.UpdatedBy
        };
    }
}
