using System.ComponentModel.DataAnnotations;

namespace HRMS.Application.DTOs;

public class EmployeePayrollProfileDto
{
    public Guid Id { get; set; }
    public Guid EmployeeId { get; set; }
    public string EmployeeNo { get; set; } = string.Empty;
    public string EmployeeName { get; set; } = string.Empty;
    public Guid EmployeeTypeId { get; set; }
    public string EmployeeTypeName { get; set; } = string.Empty;
    public string? ShiftType { get; set; }
    public string? BankAccount { get; set; }
    public string PayrollStatus { get; set; } = string.Empty;
    public DateTime? JoinPayrollDate { get; set; }
    public DateTime? LeavePayrollDate { get; set; }
    public string? Remark { get; set; }
    public DateTime CreatedAt { get; set; }
}

public class CreateEmployeePayrollProfileDto
{
    [Required(ErrorMessage = "员工不能为空")]
    public Guid EmployeeId { get; set; }

    [Required(ErrorMessage = "员工类型不能为空")]
    public Guid EmployeeTypeId { get; set; }

    public string? ShiftType { get; set; }
    public string? BankAccount { get; set; }
    public string PayrollStatus { get; set; } = "Active";
    public DateTime? JoinPayrollDate { get; set; }
    public DateTime? LeavePayrollDate { get; set; }
    public string? Remark { get; set; }
}

public class UpdateEmployeePayrollProfileDto : CreateEmployeePayrollProfileDto
{
    public Guid Id { get; set; }
}

public class AttendanceDto
{
    public Guid Id { get; set; }
    public Guid EmployeeId { get; set; }
    public string EmployeeNo { get; set; } = string.Empty;
    public string EmployeeName { get; set; } = string.Empty;
    public DateTime WorkDate { get; set; }
    public decimal NormalHours { get; set; }
    public decimal OvertimeHours { get; set; }
    public string? OvertimeType { get; set; }
    public decimal PieceworkQty { get; set; }
    public string? ShiftType { get; set; }
    public bool IsNightShift { get; set; }
    public string AttendanceSource { get; set; } = string.Empty;
    public string? SourceRecordId { get; set; }
    public string Status { get; set; } = string.Empty;
    public string? Remark { get; set; }
    public DateTime CreatedAt { get; set; }
}

public class CreateAttendanceDto
{
    [Required(ErrorMessage = "员工不能为空")]
    public Guid EmployeeId { get; set; }

    [Required(ErrorMessage = "工作日期不能为空")]
    public DateTime WorkDate { get; set; }

    public decimal NormalHours { get; set; }
    public decimal OvertimeHours { get; set; }
    public string? OvertimeType { get; set; }
    public decimal PieceworkQty { get; set; }
    public string? ShiftType { get; set; }
    public bool IsNightShift { get; set; }
    public string AttendanceSource { get; set; } = "Manual";
    public string? SourceRecordId { get; set; }
    public string Status { get; set; } = "Draft";
    public string? Remark { get; set; }
}

public class UpdateAttendanceDto : CreateAttendanceDto
{
    public Guid Id { get; set; }
}

public class SalaryAdjustmentDto
{
    public Guid Id { get; set; }
    public Guid EmployeeId { get; set; }
    public string EmployeeNo { get; set; } = string.Empty;
    public string EmployeeName { get; set; } = string.Empty;
    public string YearMonth { get; set; } = string.Empty;
    public string AdjustmentType { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    public string SourceType { get; set; } = string.Empty;
    public string? SourceId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? Remark { get; set; }
    public string? CreatedBy { get; set; }
    public DateTime CreatedAt { get; set; }
    public string? UpdatedBy { get; set; }
}

public class CreateSalaryAdjustmentDto
{
    [Required(ErrorMessage = "员工不能为空")]
    public Guid EmployeeId { get; set; }

    [Required(ErrorMessage = "年月不能为空")]
    [RegularExpression(@"^\d{4}-\d{2}$", ErrorMessage = "年月格式应为 YYYY-MM")]
    public string YearMonth { get; set; } = string.Empty;

    [Required(ErrorMessage = "调整项类型不能为空")]
    public string AdjustmentType { get; set; } = string.Empty;

    public decimal Amount { get; set; }
    public string SourceType { get; set; } = "Manual";
    public string? SourceId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? Remark { get; set; }
    public string? CreatedBy { get; set; }
}

public class UpdateSalaryAdjustmentDto : CreateSalaryAdjustmentDto
{
    public Guid Id { get; set; }
    public string? UpdatedBy { get; set; }
}
